server:
  port: 8000
  host: "0.0.0.0"
  cors:
    origins: ["*"]
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    headers: ["*"]
    credentials: true

database:
  type: "sqlite"
  sqlite:
    path: "/usr/src/app/data/donetick.db"

auth:
  jwt:
    secret: "your-secret-key-here"  # Change this to a secure random string
    expiration: 168h  # 7 days

email:
  enabled: false
  smtp:
    host: ""
    port: 587
    username: ""
    password: ""
    from: ""

logging:
  level: "info"
  format: "text"  # or "json"
  
storage:
  type: "local"
  local:
    path: "/config"